name: Validate item ID/meta upgrade schemas

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2

    - name: Install ajv-cli
      run: npm install -g ajv-cli

    - name: Validate item ID/meta upgrade schemas
      run: |
        exit_code=0

        for i in $(ls nbt_upgrade_schema); do
          ajv validate -s id_meta_upgrade_schema_schema.json -d id_meta_upgrade_schema/$i || exit_code=1
        done

        exit $exit_code
